M48
; DRILL file {KiCad 9.0.3-9.0.3-0~ubuntu24.04.1} date 2025-08-07T22:47:53-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-07T22:47:53-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3-9.0.3-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X67.5Y-67.5
X67.5Y-142.5
X142.5Y-67.5
X142.5Y-142.5
M30
